age=19
height=5.7
complex_number=1+2j
is_student=True
first_name="Ishika"
fruits=["apple","banana","orange"]
colors=("red","green","blue")
numbers={1,2,3,4,5}
student={"name":"Ishika","age":19,"is_student":True}
print(age)
print(height)
print(complex_number)
print(is_student)
print(first_name)
print(fruits)
print(colors)
print(numbers)
print(student)
